export const STATUS_MAP = {
    1: { label: "Bekliyor", color: "#64748b" },
    2: { label: "Onaylandı", color: "#0ea5e9" },
    3: { label: "Spot Araç Planlamada", color: "#f59e0b" },
    4: { label: "Araç Atandı", color: "#8b5cf6" },
    5: { label: "Araç Yüklendi", color: "#10b981" },
    6: { label: "Araç Yolda", color: "#3b82f6" },
    7: { label: "Teslim Edildi", color: "#059669" },
    8: { label: "Tamamlandı", color: "#0f172a" },
    10: { label: "Eksik Evrak", color: "#ef4444" },
    20: { label: "Teslim Edildi", color: "#059669" },
    30: { label: "Tamamlandı", color: "#0f172a" },
    40: { label: "Orijinal Evrak Geldi", color: "#6366f1" },
    50: { label: "Evrak Arşivlendi", color: "#475569" },
    80: { label: "Araç Boşaltmada", color: "#f97316" },
    90: { label: "Filo Araç Planlamada", color: "#ec4899" },
    200: { label: "İptal", color: "#b91c1c" },
};

// ✅ Region key'leri: Türkçe karakter varsa STRING KEY yaptım (tırnaklı)
// Böylece encoding bozulsa bile Babel identifier parsing yapmıyor.
export const REGIONS = {
    TRAKYA: [
        "BUNGE LÜLEBURGAZ FTL",
        "BUNGE GEBZE FTL",
        "BUNGE PALET",
        "REKA FTL",
        "EKSUN GIDA FTL",
        "SARUHAN FTL",
        "PEPSİ FTL",
        "PEPSİ FTL ÇORLU",
        "TEKİRDAĞ UN FTL",
        "AYDINLI MODA FTL",
        "ADKOTURK FTL",
        "ADKOTURK FTL ENERJİ İÇECEĞİ",
        "SGS FTL",
        "BSH FTL",
        "ALTERNA GIDA FTL",
        "BİLEŞİM KİMYA FTL",
        "DERYA OFİS FTL",
        "SAPRO FTL",
        "MARMARA CAM FTL",
        "FAKİR FTL",
        "MODERN KARTON FTL",
        "KÜÇÜKBAY TRAKYA FTL",
        "MODERN BOBİN FTL",
        "SUDESAN FTL",
    ],

    GEBZE: [
        "HEDEF FTL",
        "HEDEF DIŞ TEDARİK",
        "PEPSİ FTL GEBZE",
        "EBEBEK FTL GEBZE",
        "FAKİR FTL GEBZE",
        "MİLHANS FTL",
        "AYDIN KURUYEMİŞ FTL",
        "AVANSAS FTL",
        "AVANSAS SPOT FTL",
        "DSV ERNAMAŞ FTL",
        "FLO FTL",
        "ÇİÇEKÇİ FTL",
        "ÇİZMECİ GIDA FTL",
        "OTTONYA (HEDEFTEN AÇILIYOR)",
        "GALEN ÇOCUK FTL",
        "ENTAŞ FTL",
        "NAZAR KİMYA FTL",
    ],

    "DERİNCE": [
        "ARKAS PETROL OFİSİ DERİNCE FTL",
        "ARKAS PETROL OFİSİ DIŞ TERMİNAL FTL",
        "ARKAS TOGG",
        "ARKAS SPOT FTL",
    ],

    "İZMİR": [
        "EURO GIDA FTL",
        "EBEBEK FTL",
        "KİPAŞ SÖKE FTL",
        "CEYSU FTL",
        "TAT GIDA FTL",
        "ZER SALÇA",
        "ANKUTSAN FTL",
        "PELAGOS GIDA FTL",
        "KÜÇÜKBAY İZMİR FTL",
    ],

    "ÇUKUROVA": [
        "PEKER FTL",
        "GDP FTL",
        "ÖZMEN UN FTL",
        "KİPAŞ MARAŞ FTL",
        "TÜRK OLUKLU FTL",
        "İLKON TEKSTİL FTL",
        "BİM / MERSİN",
    ],

    "ESKİŞEHİR": [
        "ES FTL",
        "ES GLOBAL FRİGO FTL",
        "KİPAŞ BOZÜYÜK FTL",
        "2A TÜKETİM FTL",
        "MODERN HURDA DÖNÜŞ FTL",
        "MODERN HURDA ZONGULDAK FTL",
        "ŞİŞECAM FTL",
        "DENTAŞ FTL",
        "MODERN AMBALAJ FTL",
    ],

    "İÇ ANADOLU": ["APAK FTL", "SER DAYANIKLI FTL", "UNIFO FTL", "UNIFO ASKERİ FTL"],

    AFYON: ["BİM AFYON PLATFORM FTL"],

    "DİĞER": ["DOĞTAŞ İNEGÖL FTL", "AKTÜL FTL"],
};
